import pathlib
f = pathlib.Path("dashboard/index.html").open("a", encoding="utf-8")
def w(s=""): f.write(s + "\n")

# ═════════════════════════════════════════════════════════════════════════════
# JAVASCRIPT
# ═════════════════════════════════════════════════════════════════════════════
w('<script>')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// State')
w('// ─────────────────────────────────────────────────────────────────────────')
w('let allResults = []; // Array of all benchmark run summaries')
w('let baselineData = null; // Second most recent')
w('let specData = null;     // Most recent')
w('let selectedRunForJson = null;')
w('let benchmarkEventSource = null;')
w('let serverOnline = false;')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// Utils')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function $(id) { return document.getElementById(id); }')
w('function fmtDate(iso) {')
w('  if (!iso) return "N/A";')
w('  const d = new Date(iso);')
w('  return d.toLocaleString("en-US", { month:"short", day:"numeric", hour:"2-digit", minute:"2-digit" });')
w('}')
w('function fmtNum(n, decimals=2) {')
w('  if (typeof n !== "number" || isNaN(n)) return "—";')
w('  return n.toFixed(decimals);')
w('}')
w('function fmtPct(n) {')
w('  if (typeof n !== "number" || isNaN(n)) return "—";')
w('  return n.toFixed(1) + "%";')
w('}')
w('function escapeHtml(str) {')
w('  const div = document.createElement("div");')
w('  div.textContent = str;')
w('  return div.innerHTML;')
w('}')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// Navigation')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function showSection(name) {')
w('  ["overview", "benchmark", "try-it", "history"].forEach(s => {')
w('    const el = $("section-" + s);')
w('    if (el) el.style.display = (s === name) ? "block" : "none";')
w('  });')
w('  document.querySelectorAll(".nav-tab").forEach(t => {')
w('    t.classList.toggle("active", t.dataset.section === name);')
w('  });')
w('}')
w('document.querySelectorAll(".nav-tab").forEach(tab => {')
w('  tab.addEventListener("click", () => showSection(tab.dataset.section));')
w('});')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// Status polling')
w('// ─────────────────────────────────────────────────────────────────────────')
w('async function checkStatus() {')
w('  try {')
w('    const res = await fetch("/api/status");')
w('    if (!res.ok) throw new Error(res.statusText);')
w('    const data = await res.json();')
w('    serverOnline = data.llama_server && data.llama_server.ok;')
w('    const dot = $("statusDot");')
w('    const txt = $("statusText");')
w('    if (serverOnline) {')
w('      dot.className = "dot online";')
w('      txt.textContent = "Server Live";')
w('    } else {')
w('      dot.className = "dot offline";')
w('      txt.textContent = "Server Offline";')
w('    }')
w('    $("offlineNote").classList.toggle("hidden", serverOnline);')
w('  } catch (err) {')
w('    console.error("[status]", err);')
w('    $("statusDot").className = "dot offline";')
w('    $("statusText").textContent = "Unreachable";')
w('    $("offlineNote").classList.remove("hidden");')
w('  }')
w('}')
w('setInterval(checkStatus, 10000);')
w('checkStatus();')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// Load system info')
w('// ─────────────────────────────────────────────────────────────────────────')
w('async function loadSysinfo() {')
w('  try {')
w('    const res = await fetch("/api/sysinfo");')
w('    if (!res.ok) throw new Error(res.statusText);')
w('    const data = await res.json();')
w('    const s = data.summary || {};')
w('    $("si-cpu").textContent = s.cpu || "N/A";')
w('    $("si-cpu").classList.remove("skeleton", "skeleton-value");')
w('    $("si-cores").textContent = s.cores || "N/A";')
w('    $("si-cores").classList.remove("skeleton", "skeleton-text");')
w('    $("si-memory").textContent = s.memory || "N/A";')
w('    $("si-memory").classList.remove("skeleton", "skeleton-text");')
w('    $("si-os").textContent = (s.os || "N/A") + " / " + (s.arch || "N/A");')
w('    $("si-os").classList.remove("skeleton", "skeleton-text");')
w('    $("si-kleidiai").textContent = s.kleidiai || "N/A";')
w('    $("si-kleidiai").classList.remove("skeleton", "skeleton-text");')
w('')
w('    const pills = $("featurePills");')
w('    pills.innerHTML = "";')
w('    const features = [')
w('      { name: "NEON", val: s.neon },')
w('      { name: "DOTPROD", val: s.dotprod },')
w('      { name: "SVE", val: s.sve },')
w('      { name: "I8MM", val: s.i8mm },')
w('    ];')
w('    features.forEach(ft => {')
w('      const pill = document.createElement("div");')
w('      pill.className = "pill " + (ft.val ? "green" : "red");')
w('      pill.textContent = ft.name;')
w('      pills.appendChild(pill);')
w('    });')
w('  } catch (err) {')
w('    console.error("[sysinfo]", err);')
w('  }')
w('}')
w('loadSysinfo();')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// Load benchmark results')
w('// ─────────────────────────────────────────────────────────────────────────')
w('async function loadResults() {')
w('  try {')
w('    const res = await fetch("/api/results");')
w('    if (!res.ok) throw new Error(res.statusText);')
w('    const data = await res.json();')
w('    allResults = data.runs || [];')
w('    if (allResults.length >= 1) specData = allResults[0];')
w('    if (allResults.length >= 2) baselineData = allResults[1];')
w('    renderComparison();')
w('    renderChart();')
w('    renderHistoryTable();')
w('    $("footerResultCount").textContent = `${allResults.length} benchmark run(s) saved`;')
w('  } catch (err) {')
w('    console.error("[results]", err);')
w('  }')
w('}')
w('loadResults();')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// Render comparison cards')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function renderComparison() {')
w('  // Baseline (left)')
w('  if (baselineData) {')
w('    $("baselineMetrics").innerHTML = `')
w('      <div class="metric-row"><span class="metric-label">Avg TPS</span><span class="metric-value">${fmtNum(baselineData.avg_tps)}</span></div>')
w('      <div class="metric-row"><span class="metric-label">Median TPS</span><span class="metric-value">${fmtNum(baselineData.median_tps)}</span></div>')
w('      <div class="metric-row"><span class="metric-label">P95 TPS</span><span class="metric-value">${fmtNum(baselineData.p95_tps)}</span></div>')
w('      <div class="metric-row"><span class="metric-label">Duration (avg)</span><span class="metric-value">${fmtNum(baselineData.avg_duration_sec, 3)}s</span></div>')
w('      <div class="metric-row"><span class="metric-label">Success Rate</span><span class="metric-value green">${fmtPct(baselineData.success_rate)}</span></div>')
w('    `;')
w('  }')
w('  // Speculative (right)')
w('  if (specData) {')
w('    $("specMetrics").innerHTML = `')
w('      <div class="metric-row"><span class="metric-label">Avg TPS</span><span class="metric-value highlight">${fmtNum(specData.avg_tps)}</span></div>')
w('      <div class="metric-row"><span class="metric-label">Median TPS</span><span class="metric-value highlight">${fmtNum(specData.median_tps)}</span></div>')
w('      <div class="metric-row"><span class="metric-label">P95 TPS</span><span class="metric-value highlight">${fmtNum(specData.p95_tps)}</span></div>')
w('      <div class="metric-row"><span class="metric-label">Duration (avg)</span><span class="metric-value">${fmtNum(specData.avg_duration_sec, 3)}s</span></div>')
w('      <div class="metric-row"><span class="metric-label">Success Rate</span><span class="metric-value green">${fmtPct(specData.success_rate)}</span></div>')
w('    `;')
w('  }')
w('  // Speedup badge')
w('  if (specData && baselineData) {')
w('    const diffPct = ((specData.avg_tps / baselineData.avg_tps - 1) * 100);')
w('    const cls = diffPct >= 0 ? "speedup-badge" : "speedup-badge negative";')
w('    const sign = diffPct >= 0 ? "+" : "";')
w('    $("speedupBadge").innerHTML = `<div class="${cls}">${sign}${fmtNum(diffPct, 1)}%</div>`;')
w('  } else {')
w('    $("speedupBadge").innerHTML = "";')
w('  }')
w('}')
w('')

f.close()
print("JS part 1 written")
