import pathlib
f = pathlib.Path("dashboard/index.html").open("a", encoding="utf-8")
def w(s=""): f.write(s + "\n")

# ─────────────────────────────────────────────────────────────────────────
# SVG Bar Chart
# ─────────────────────────────────────────────────────────────────────────
w('// ─────────────────────────────────────────────────────────────────────────')
w('// SVG Bar Chart: tokens/sec by category')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function renderChart() {')
w('  const svg = $("category-chart");')
w('  svg.innerHTML = "";')
w('')
w('  const CATEGORIES = ["short_qa", "coding", "math", "reasoning", "long_generation", "chat", "summarization"];')
w('  const LABELS     = { short_qa:"Short QA", coding:"Coding", math:"Math", reasoning:"Reasoning",')
w('                        long_generation:"Long Gen", chat:"Chat", summarization:"Summary" };')
w('')
w('  // Gather data')
w('  const specCatTps     = specData     ? (specData.category_tps     || {}) : {};')
w('  const baselineCatTps = baselineData ? (baselineData.category_tps || {}) : {};')
w('')
w('  const presentCats = CATEGORIES.filter(c =>')
w('    specCatTps[c] !== undefined || baselineCatTps[c] !== undefined')
w('  );')
w('  if (presentCats.length === 0) {')
w('    const text = document.createElementNS("http://www.w3.org/2000/svg", "text");')
w('    text.setAttribute("x", "50%");')
w('    text.setAttribute("y", "50%");')
w('    text.setAttribute("text-anchor", "middle");')
w('    text.setAttribute("fill", "#6e7681");')
w('    text.setAttribute("font-size", "13");')
w('    text.setAttribute("font-family", "system-ui");')
w('    text.textContent = "No category data yet — run a benchmark to populate the chart.";')
w('    svg.appendChild(text);')
w('    svg.setAttribute("height", "100");')
w('    return;')
w('  }')
w('')
w('  // Layout constants')
w('  const W = svg.parentElement ? svg.parentElement.offsetWidth : 700;')
w('  const H = 240;')
w('  const MARGIN = { top: 20, right: 20, bottom: 50, left: 50 };')
w('  const chartW = W - MARGIN.left - MARGIN.right;')
w('  const chartH = H - MARGIN.top - MARGIN.bottom;')
w('')
w('  svg.setAttribute("width", W);')
w('  svg.setAttribute("height", H);')
w('  svg.setAttribute("viewBox", `0 0 ${W} ${H}`);')
w('')
w('  // Scale')
w('  const allVals = presentCats.flatMap(c => [specCatTps[c] || 0, baselineCatTps[c] || 0]);')
w('  const maxVal  = Math.max(...allVals, 1) * 1.15;')
w('')
w('  const ns = "http://www.w3.org/2000/svg";')
w('')
w('  function svgEl(tag, attrs) {')
w('    const el = document.createElementNS(ns, tag);')
w('    Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k, v));')
w('    return el;')
w('  }')
w('')
w('  // Root group')
w('  const g = svgEl("g", { transform: `translate(${MARGIN.left},${MARGIN.top})` });')
w('')
w('  // Y-axis gridlines')
w('  const yTicks = 5;')
w('  for (let i = 0; i <= yTicks; i++) {')
w('    const y = chartH - (i / yTicks) * chartH;')
w('    const val = (i / yTicks) * maxVal;')
w('    // grid line')
w('    g.appendChild(svgEl("line", {')
w('      x1: 0, y1: y, x2: chartW, y2: y,')
w('      stroke: "#30363d", "stroke-width": 1,')
w('    }));')
w('    // y label')
w('    const yt = svgEl("text", {')
w('      x: -6, y: y + 4,')
w('      "text-anchor": "end",')
w('      fill: "#6e7681",')
w('      "font-size": 10,')
w('      "font-family": "system-ui",')
w('    });')
w('    yt.textContent = val.toFixed(0);')
w('    g.appendChild(yt);')
w('  }')
w('')
w('  // Bars')
w('  const nCats  = presentCats.length;')
w('  const groupW = chartW / nCats;')
w('  const bw     = Math.min(groupW * 0.38, 30); // bar width')
w('  const gap    = Math.min(groupW * 0.06, 4);')
w('')
w('  presentCats.forEach((cat, i) => {')
w('    const gx = i * groupW + groupW / 2;')
w('')
w('    // Draw baseline bar (gray)')
w('    const bv = baselineCatTps[cat] || 0;')
w('    if (bv > 0) {')
w('      const bh = (bv / maxVal) * chartH;')
w('      const rect = svgEl("rect", {')
w('        x: gx - gap - bw,')
w('        y: chartH - bh,')
w('        width: bw,')
w('        height: bh,')
w('        fill: "#484f58",')
w('        rx: 2,')
w('        "data-val": bv,')
w('      });')
w('      rect.style.transition = "opacity .2s";')
w('      // tooltip via title')
w('      const title = document.createElementNS(ns, "title");')
w('      title.textContent = `Baseline ${LABELS[cat]}: ${bv.toFixed(2)} tok/s`;')
w('      rect.appendChild(title);')
w('      g.appendChild(rect);')
w('    }')
w('')
w('    // Draw speculative bar (accent blue)')
w('    const sv = specCatTps[cat] || 0;')
w('    if (sv > 0) {')
w('      const sh = (sv / maxVal) * chartH;')
w('      const rect2 = svgEl("rect", {')
w('        x: gx + gap,')
w('        y: chartH - sh,')
w('        width: bw,')
w('        height: sh,')
w('        fill: "#58a6ff",')
w('        rx: 2,')
w('      });')
w('      const title2 = document.createElementNS(ns, "title");')
w('      title2.textContent = `Speculative ${LABELS[cat]}: ${sv.toFixed(2)} tok/s`;')
w('      rect2.appendChild(title2);')
w('      g.appendChild(rect2);')
w('    }')
w('')
w('    // X label')
w('    const xt = svgEl("text", {')
w('      x: gx,')
w('      y: chartH + 16,')
w('      "text-anchor": "middle",')
w('      fill: "#8b949e",')
w('      "font-size": 10,')
w('      "font-family": "system-ui",')
w('    });')
w('    xt.textContent = LABELS[cat] || cat;')
w('    g.appendChild(xt);')
w('  });')
w('')
w('  // Y-axis label')
w('  const yl = svgEl("text", {')
w('    x: -(chartH / 2), y: -36,')
w('    "text-anchor": "middle",')
w('    transform: "rotate(-90)",')
w('    fill: "#6e7681",')
w('    "font-size": 10,')
w('    "font-family": "system-ui",')
w('  });')
w('  yl.textContent = "tok/s";')
w('  g.appendChild(yl);')
w('')
w('  svg.appendChild(g);')
w('}')
w('')

f.close()
print("Chart JS written")
