import pathlib
f = pathlib.Path("dashboard/index.html").open("a", encoding="utf-8")
def w(s=""): f.write(s + "\n")

w('// ─────────────────────────────────────────────────────────────────────────')
w('// History Table')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function renderHistoryTable() {')
w('  const wrap = $("historyTableWrap");')
w('  if (!allResults || allResults.length === 0) {')
w('    wrap.innerHTML = `<div style="padding:24px;color:var(--text-dim);text-align:center;">No benchmark results yet.<br>Run a benchmark to see history here.</div>`;')
w('    return;')
w('  }')
w('  let html = `<div class="table-wrap"><table>')
w('    <thead><tr>')
w('      <th>#</th>')
w('      <th>Timestamp</th>')
w('      <th>Model</th>')
w('      <th>Avg TPS</th>')
w('      <th>Median TPS</th>')
w('      <th>P95 TPS</th>')
w('      <th>Success</th>')
w('      <th>Trials</th>')
w('      <th>Max Tokens</th>')
w('    </tr></thead>')
w('    <tbody>`;')
w('  allResults.forEach((run, idx) => {')
w('    const isLatest = idx === 0;')
w('    html += `<tr class="${isLatest ? "selected" : ""}" onclick="selectHistoryRow(${idx})" data-idx="${idx}">')
w('      <td class="td-mono">${allResults.length - idx}</td>')
w('      <td class="td-mono">${fmtDate(run.timestamp)}</td>')
w('      <td>${escapeHtml(run.model || "Q4_K_M")}</td>')
w('      <td style="color:var(--accent);font-weight:700">${fmtNum(run.avg_tps)}</td>')
w('      <td>${fmtNum(run.median_tps)}</td>')
w('      <td>${fmtNum(run.p95_tps)}</td>')
w('      <td><span class="pill green">${fmtPct(run.success_rate)}</span></td>')
w('      <td>${run.trials || "—"}</td>')
w('      <td>${run.max_tokens || "—"}</td>')
w('    </tr>`;')
w('  });')
w('  html += "</tbody></table></div>";')
w('  wrap.innerHTML = html;')
w('}')
w('')
w('// When user clicks a history row')
w('function selectHistoryRow(idx) {')
w('  // Highlight row')
w('  document.querySelectorAll("#historyTableWrap tbody tr").forEach((tr, i) => {')
w('    tr.classList.toggle("selected", i === idx);')
w('  });')
w('  // Update comparison: selected row as baseline, most recent as spec')
w('  if (idx === 0) {')
w('    baselineData = allResults.length >= 2 ? allResults[1] : null;')
w('    specData = allResults[0];')
w('  } else {')
w('    baselineData = allResults[idx];')
w('    specData = allResults[0];')
w('  }')
w('  renderComparison();')
w('  renderChart();')
w('  showSection("overview");')
w('  // Load JSON viewer')
w('  loadJsonForFile(allResults[idx].filename);')
w('}')
w('')
w('// ─────────────────────────────────────────────────────────────────────────')
w('// JSON Viewer')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function toggleJsonViewer() {')
w('  const viewer = $("jsonViewer");')
w('  const chevron = $("jsonChevron");')
w('  const isOpen = viewer.classList.contains("open");')
w('  viewer.classList.toggle("open", !isOpen);')
w('  chevron.classList.toggle("open", !isOpen);')
w('}')
w('')
w('async function loadJsonForFile(filename) {')
w('  if (!filename) return;')
w('  $("jsonToggle").style.display = "flex";')
w('  $("jsonFilename").textContent = filename;')
w('  $("jsonViewer").classList.add("open");')
w('  $("jsonChevron").classList.add("open");')
w('  $("jsonContent").textContent = "Loading...";')
w('  try {')
w('    const res = await fetch("/api/results/" + encodeURIComponent(filename) + "?full=1");')
w('    if (!res.ok) throw new Error(res.statusText);')
w('    const data = await res.json();')
w('    $("jsonContent").innerHTML = syntaxHighlightJson(JSON.stringify(data, null, 2));')
w('  } catch (err) {')
w('    $("jsonContent").textContent = "Error loading JSON: " + err.message;')
w('  }')
w('}')
w('')
w('// Basic JSON syntax highlighter using regex replacement')
w('function syntaxHighlightJson(json) {')
w('  return escapeHtml(json)')
w('    .replace(/"([^"]+)"\\s*:/g, \'<span class="json-key">"$1"</span>:\')')
w('    .replace(/:\\s*"([^"]*)"/g, \': <span class="json-str">"$1"</span>\')')
w('    .replace(/:\\s*(-?\\d+\\.?\\d*)/g, \': <span class="json-num">$1</span>\')')
w('    .replace(/:\\s*(true|false)/g, \': <span class="json-bool">$1</span>\')')
w('    .replace(/:\\s*(null)/g, \': <span class="json-null">$1</span>\');')
w('}')
w('')

f.close()
print("History+JSON JS written")
