import pathlib
f = pathlib.Path("dashboard/index.html").open("a", encoding="utf-8")
def w(s=""): f.write(s + "\n")

w('// ─────────────────────────────────────────────────────────────────────────')
w('// Benchmark Runner')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function toggleBenchConfig() {')
w('  const cfg = $("benchConfig");')
w('  const isOpen = cfg.classList.contains("open");')
w('  cfg.classList.toggle("open", !isOpen);')
w('}')
w('')
w('async function startBenchmark() {')
w('  const url       = $("cfgServerUrl").value.trim();')
w('  const model     = $("cfgModel").value.trim();')
w('  const trials    = parseInt($("cfgTrials").value, 10) || 3;')
w('  const maxTokens = parseInt($("cfgMaxTokens").value, 10) || 64;')
w('')
w('  if (!url) {')
w('    alert("Please enter a server URL");')
w('    return;')
w('  }')
w('')
w('  // Disable buttons')
w('  $("btnRunBench").disabled = true;')
w('  $("btnStartBench").disabled = true;')
w('  $("btnCancelBench").style.display = "inline-flex";')
w('  $("benchConfig").classList.remove("open");')
w('')
w('  // Show log terminal')
w('  const log = $("logTerminal");')
w('  log.classList.add("open");')
w('  log.textContent = "";')
w('')
w('  // Start benchmark')
w('  try {')
w('    const res = await fetch("/api/benchmark", {')
w('      method: "POST",')
w('      headers: { "Content-Type": "application/json" },')
w('      body: JSON.stringify({ server_url: url, model, trials, max_tokens: maxTokens }),')
w('    });')
w('    if (!res.ok) {')
w('      const err = await res.text();')
w('      log.textContent += "\\n[ERROR] " + err;')
w('      resetBenchmarkUI();')
w('      return;')
w('    }')
w('    const data = await res.json();')
w('    log.textContent += data.message + "\\n";')
w('  } catch (err) {')
w('    log.textContent += "\\n[FETCH ERROR] " + err.message;')
w('    resetBenchmarkUI();')
w('    return;')
w('  }')
w('')
w('  // Connect to SSE stream')
w('  benchmarkEventSource = new EventSource("/api/benchmark/stream");')
w('  benchmarkEventSource.addEventListener("message", evt => {')
w('    const data = JSON.parse(evt.data);')
w('    if (data.type === "connected") {')
w('      log.textContent += "[Connected to benchmark stream]\\n";')
w('    } else if (data.type === "log") {')
w('      log.textContent += data.line + "\\n";')
w('      log.scrollTop = log.scrollHeight;')
w('    } else if (data.type === "done") {')
w('      if (data.ok) {')
w('        log.textContent += "\\n✅ Benchmark complete!\\n";')
w('        // Refresh results')
w('        loadResults();')
w('      } else {')
w('        log.textContent += "\\n❌ Benchmark failed. Exit code: " + (data.exit_code || "unknown") + "\\n";')
w('      }')
w('      resetBenchmarkUI();')
w('    } else if (data.type === "ping") {')
w('      // heartbeat')
w('    }')
w('  });')
w('  benchmarkEventSource.addEventListener("error", () => {')
w('    log.textContent += "\\n[SSE connection error or closed]\\n";')
w('    resetBenchmarkUI();')
w('  });')
w('}')
w('')
w('function cancelBenchmark() {')
w('  if (benchmarkEventSource) {')
w('    benchmarkEventSource.close();')
w('    benchmarkEventSource = null;')
w('    $("logTerminal").textContent += "\\n[Cancelled by user]\\n";')
w('  }')
w('  resetBenchmarkUI();')
w('}')
w('')
w('function resetBenchmarkUI() {')
w('  $("btnRunBench").disabled = false;')
w('  $("btnStartBench").disabled = false;')
w('  $("btnCancelBench").style.display = "none";')
w('  if (benchmarkEventSource) {')
w('    benchmarkEventSource.close();')
w('    benchmarkEventSource = null;')
w('  }')
w('}')
w('')

f.close()
print("Benchmark runner JS written")
