import pathlib
f = pathlib.Path("dashboard/index.html").open("a", encoding="utf-8")
def w(s=""): f.write(s + "\n")

w('// ─────────────────────────────────────────────────────────────────────────')
w('// Try It Live — single prompt')
w('// ─────────────────────────────────────────────────────────────────────────')
w('function setPreset(btn) {')
w('  $("promptInput").value = btn.textContent;')
w('}')
w('')
w('async function sendPrompt() {')
w('  const prompt = $("promptInput").value.trim();')
w('  if (!prompt) { alert("Please enter a prompt."); return; }')
w('')
w('  const url       = $("tryServerUrl").value.trim() || "http://13.211.208.159:8080";')
w('  const maxTokens = parseInt($("tryMaxTokens").value, 10) || 256;')
w('  const temp      = parseFloat($("tryTemp").value) || 0.7;')
w('')
w('  const btn = $("btnSendPrompt");')
w('  btn.disabled = true;')
w('  btn.innerHTML = `<div class="spinner sm"></div> Generating...`;')
w('')
w('  const respBox = $("responseBox");')
w('  const respContent = $("responseContent");')
w('  const respMeta = $("responseMeta");')
w('  respBox.classList.add("open");')
w('  respContent.textContent = "";')
w('  respMeta.innerHTML = `<div class="flex-center gap-8"><div class="spinner sm"></div> <span style="color:var(--text-dim)">Waiting for response...</span></div>`;')
w('')
w('  try {')
w('    const res = await fetch("/api/prompt", {')
w('      method: "POST",')
w('      headers: { "Content-Type": "application/json" },')
w('      body: JSON.stringify({')
w('        prompt,')
w('        max_tokens: maxTokens,')
w('        temperature: temp,')
w('        server_url: url,')
w('      }),')
w('    });')
w('    const data = await res.json();')
w('    if (data.ok) {')
w('      respContent.textContent = data.content || "(empty response)";')
w('      respMeta.innerHTML = `')
w('        <div class="response-meta-item">⚡ <strong>${fmtNum(data.tokens_per_second)}</strong> tok/s</div>')
w('        <div class="response-meta-item">⏱ <strong>${fmtNum(data.duration_sec, 3)}s</strong> duration</div>')
w('        <div class="response-meta-item">�� <strong>${data.tokens_generated}</strong> tokens generated</div>')
w('        <div class="response-meta-item">📥 <strong>${data.tokens_prompt}</strong> prompt tokens</div>')
w('      `;')
w('    } else {')
w('      respContent.textContent = "Error: " + (data.error || "Unknown error");')
w('      respMeta.innerHTML = "";')
w('    }')
w('  } catch (err) {')
w('    respContent.textContent = "Request failed: " + err.message;')
w('    respMeta.innerHTML = "";')
w('  } finally {')
w('    btn.disabled = false;')
w('    btn.innerHTML = `<span>&#x27A4;</span> Send Prompt`;')
w('  }')
w('}')
w('')
w('function clearResponse() {')
w('  $("responseBox").classList.remove("open");')
w('  $("responseContent").textContent = "";')
w('  $("responseMeta").innerHTML = "";')
w('  $("promptInput").value = "";')
w('}')
w('')
w('// Allow Enter key in textarea to send (Shift+Enter for newline)')
w('$("promptInput").addEventListener("keydown", function(e) {')
w('  if (e.key === "Enter" && !e.shiftKey) {')
w('    e.preventDefault();')
w('    sendPrompt();')
w('  }')
w('});')
w('')

f.close()
print("Prompt JS written")
