import pathlib
f = pathlib.Path("dashboard/index.html").open("a", encoding="utf-8")
def w(s=""): f.write(s + "\n")

w('// ─────────────────────────────────────────────────────────────────────────')
w('// Init & resize handling')
w('// ─────────────────────────────────────────────────────────────────────────')
w('')
w('// On window resize, re-render chart')
w('let resizeTimer;')
w('window.addEventListener("resize", () => {')
w('  clearTimeout(resizeTimer);')
w('  resizeTimer = setTimeout(() => renderChart(), 200);')
w('});')
w('')
w('// Show all sections initially, then hide non-overview')
w('showSection("overview");')
w('')
w('</script>')
w('</body>')
w('</html>')

f.close()
print("HTML finalized")
