import pathlib, sys

OUT = pathlib.Path("dashboard/index.html")
f = OUT.open("w", encoding="utf-8")

def w(s=""):
    f.write(s + "\n")

# ── HEAD ──────────────────────────────────────────────────────────────────────
w('<!DOCTYPE html>')
w('<html lang="en">')
w('<head>')
w('<meta charset="UTF-8" />')
w('<meta name="viewport" content="width=device-width, initial-scale=1.0" />')
w('<title>SpecArm — Arm AI Optimization Dashboard</title>')
w('<style>')
# ─── CSS Reset & Base ────────────────────────────────────────────────────────
w('*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }')
w(':root {')
w('  --bg:        #0d1117;')
w('  --card:      #161b22;')
w('  --card2:     #1c2128;')
w('  --border:    #30363d;')
w('  --accent:    #58a6ff;')
w('  --arm:       #0091BD;')
w('  --green:     #3fb950;')
w('  --red:       #f85149;')
w('  --yellow:    #d29922;')
w('  --text:      #e6edf3;')
w('  --text-dim:  #8b949e;')
w('  --text-sub:  #6e7681;')
w('  --radius:    8px;')
w('  --radius-lg: 12px;')
w('  --shadow:    0 8px 24px rgba(0,0,0,.4);')
w('}')
w('html { scroll-behavior: smooth; }')
w('body {')
w('  background: var(--bg);')
w('  color: var(--text);')
w('  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;')
w('  font-size: 14px;')
w('  line-height: 1.6;')
w('  min-height: 100vh;')
w('}')

# ─── Layout ──────────────────────────────────────────────────────────────────
w('.container { max-width: 1280px; margin: 0 auto; padding: 0 24px; }')
w('.grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }')
w('.grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; }')
w('@media (max-width: 900px) { .grid-2, .grid-3 { grid-template-columns: 1fr; } }')
w('.flex { display: flex; }')
w('.flex-center { display: flex; align-items: center; }')
w('.flex-between { display: flex; align-items: center; justify-content: space-between; }')
w('.gap-8 { gap: 8px; }')
w('.gap-12 { gap: 12px; }')
w('.gap-16 { gap: 16px; }')
w('.mt-8 { margin-top: 8px; }')
w('.mt-16 { margin-top: 16px; }')
w('.mt-24 { margin-top: 24px; }')
w('.mb-8 { margin-bottom: 8px; }')
w('.mb-16 { margin-bottom: 16px; }')

# ─── Header ──────────────────────────────────────────────────────────────────
w('header {')
w('  background: var(--card);')
w('  border-bottom: 1px solid var(--border);')
w('  padding: 0 24px;')
w('  position: sticky;')
w('  top: 0;')
w('  z-index: 100;')
w('  box-shadow: 0 1px 0 var(--border);')
w('}')
w('.header-inner {')
w('  max-width: 1280px;')
w('  margin: 0 auto;')
w('  height: 60px;')
w('  display: flex;')
w('  align-items: center;')
w('  justify-content: space-between;')
w('}')
w('.logo { display: flex; align-items: center; gap: 12px; }')
w('.logo-mark {')
w('  width: 36px; height: 36px;')
w('  background: linear-gradient(135deg, var(--arm) 0%, var(--accent) 100%);')
w('  border-radius: 8px;')
w('  display: flex; align-items: center; justify-content: center;')
w('  font-weight: 800; font-size: 16px; color: #fff; letter-spacing: -1px;')
w('}')
w('.logo-text { display: flex; flex-direction: column; line-height: 1.2; }')
w('.logo-name { font-size: 18px; font-weight: 700; color: var(--text); }')
w('.logo-sub { font-size: 11px; color: var(--text-dim); letter-spacing: 0.3px; }')
w('.status-badge {')
w('  display: flex; align-items: center; gap: 8px;')
w('  background: var(--card2); border: 1px solid var(--border);')
w('  border-radius: 20px; padding: 6px 14px;')
w('  font-size: 12px; font-weight: 500;')
w('}')
w('.dot {')
w('  width: 8px; height: 8px; border-radius: 50%;')
w('  background: var(--text-sub);')
w('  transition: background .3s;')
w('}')
w('.dot.online { background: var(--green); box-shadow: 0 0 6px var(--green); }')
w('.dot.offline { background: var(--red); }')
w('.dot.checking { background: var(--yellow); animation: pulse 1s infinite; }')
w('@keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }')

# ─── Nav tabs ────────────────────────────────────────────────────────────────
w('.nav-tabs {')
w('  display: flex; gap: 4px; align-items: center;')
w('}')
w('.nav-tab {')
w('  padding: 6px 14px; border-radius: 6px; cursor: pointer;')
w('  font-size: 13px; color: var(--text-dim); transition: all .2s;')
w('  border: 1px solid transparent;')
w('  background: none;')
w('}')
w('.nav-tab:hover { color: var(--text); background: var(--card2); }')
w('.nav-tab.active { color: var(--accent); background: rgba(88,166,255,.1); border-color: rgba(88,166,255,.3); }')

# ─── Sections ────────────────────────────────────────────────────────────────
w('.section {')
w('  padding: 32px 0;')
w('  border-bottom: 1px solid var(--border);')
w('}')
w('.section:last-child { border-bottom: none; }')
w('.section-header { margin-bottom: 20px; }')
w('.section-title {')
w('  font-size: 20px; font-weight: 700; color: var(--text);')
w('  display: flex; align-items: center; gap: 10px;')
w('}')
w('.section-title .icon { font-size: 18px; }')
w('.section-desc { color: var(--text-dim); font-size: 13px; margin-top: 4px; }')

# ─── Cards ───────────────────────────────────────────────────────────────────
w('.card {')
w('  background: var(--card);')
w('  border: 1px solid var(--border);')
w('  border-radius: var(--radius-lg);')
w('  padding: 20px;')
w('  transition: border-color .2s;')
w('}')
w('.card:hover { border-color: #484f58; }')
w('.card-title {')
w('  font-size: 12px; font-weight: 600; text-transform: uppercase;')
w('  letter-spacing: 0.8px; color: var(--text-dim); margin-bottom: 12px;')
w('}')
w('.card-value {')
w('  font-size: 32px; font-weight: 700; color: var(--text);')
w('  letter-spacing: -1px; line-height: 1;')
w('}')
w('.card-unit { font-size: 14px; font-weight: 400; color: var(--text-dim); margin-left: 4px; }')
w('.card-sub { font-size: 12px; color: var(--text-sub); margin-top: 6px; }')

# ─── Pills / badges ──────────────────────────────────────────────────────────
w('.pill {')
w('  display: inline-flex; align-items: center; gap: 4px;')
w('  padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: 600;')
w('  letter-spacing: 0.4px;')
w('}')
w('.pill.green { background: rgba(63,185,80,.15); color: var(--green); border: 1px solid rgba(63,185,80,.3); }')
w('.pill.red   { background: rgba(248,81,73,.12); color: var(--red);   border: 1px solid rgba(248,81,73,.3); }')
w('.pill.blue  { background: rgba(88,166,255,.12); color: var(--accent); border: 1px solid rgba(88,166,255,.3); }')
w('.pill.arm   { background: rgba(0,145,189,.15); color: var(--arm); border: 1px solid rgba(0,145,189,.3); }')
w('.pill.gray  { background: rgba(139,148,158,.1); color: var(--text-dim); border: 1px solid var(--border); }')

# ─── Speedup badge ───────────────────────────────────────────────────────────
w('.speedup-badge {')
w('  display: inline-flex; align-items: center; justify-content: center;')
w('  padding: 6px 16px; border-radius: 20px;')
w('  font-size: 13px; font-weight: 700;')
w('  background: rgba(63,185,80,.15); color: var(--green);')
w('  border: 1px solid rgba(63,185,80,.3);')
w('}')
w('.speedup-badge.negative { background: rgba(248,81,73,.1); color: var(--red); border-color: rgba(248,81,73,.3); }')

# ─── Comparison section ───────────────────────────────────────────────────────
w('.compare-wrap {')
w('  display: grid;')
w('  grid-template-columns: 1fr auto 1fr;')
w('  gap: 16px;')
w('  align-items: start;')
w('}')
w('@media (max-width: 800px) {')
w('  .compare-wrap { grid-template-columns: 1fr; }')
w('  .compare-divider { display: none; }')
w('}')
w('.compare-card {')
w('  background: var(--card);')
w('  border: 1px solid var(--border);')
w('  border-radius: var(--radius-lg);')
w('  padding: 20px;')
w('  position: relative;')
w('  transition: border-color .2s, box-shadow .2s;')
w('}')
w('.compare-card.spec { border-color: rgba(88,166,255,.4); }')
w('.compare-card.spec:hover { border-color: var(--accent); box-shadow: 0 0 20px rgba(88,166,255,.1); }')
w('.compare-card.baseline:hover { border-color: #484f58; }')
w('.compare-card-header {')
w('  display: flex; align-items: flex-start; justify-content: space-between;')
w('  margin-bottom: 16px;')
w('}')
w('.compare-card-label {')
w('  font-size: 11px; font-weight: 700; text-transform: uppercase;')
w('  letter-spacing: 1px; color: var(--text-dim);')
w('  margin-bottom: 4px;')
w('}')
w('.compare-card.spec .compare-card-label { color: var(--accent); }')
w('.compare-card-model { font-size: 13px; color: var(--text); font-weight: 500; }')
w('.metric-row {')
w('  display: flex; justify-content: space-between; align-items: center;')
w('  padding: 8px 0;')
w('  border-bottom: 1px solid var(--border);')
w('}')
w('.metric-row:last-child { border-bottom: none; }')
w('.metric-label { font-size: 12px; color: var(--text-dim); }')
w('.metric-value { font-size: 14px; font-weight: 700; color: var(--text); }')
w('.metric-value.highlight { color: var(--accent); }')
w('.metric-value.green { color: var(--green); }')
w('.compare-divider {')
w('  display: flex; flex-direction: column; align-items: center;')
w('  justify-content: center; gap: 8px; padding-top: 60px;')
w('}')
w('.vs-circle {')
w('  width: 40px; height: 40px; border-radius: 50%;')
w('  background: var(--card2); border: 1px solid var(--border);')
w('  display: flex; align-items: center; justify-content: center;')
w('  font-size: 11px; font-weight: 700; color: var(--text-dim);')
w('}')
w('.empty-compare {')
w('  text-align: center; padding: 32px 16px;')
w('  color: var(--text-sub); font-size: 13px;')
w('}')
w('.empty-compare .icon { font-size: 28px; display: block; margin-bottom: 8px; }')

# ─── SVG chart ───────────────────────────────────────────────────────────────
w('.chart-wrap {')
w('  background: var(--card);')
w('  border: 1px solid var(--border);')
w('  border-radius: var(--radius-lg);')
w('  padding: 20px;')
w('  margin-top: 16px;')
w('  overflow-x: auto;')
w('}')
w('.chart-title {')
w('  font-size: 13px; font-weight: 600; color: var(--text-dim);')
w('  margin-bottom: 16px; text-transform: uppercase; letter-spacing: 0.8px;')
w('}')
w('#category-chart { width: 100%; min-width: 500px; display: block; }')

# ─── Benchmark run section ───────────────────────────────────────────────────
w('.bench-config {')
w('  background: var(--card2);')
w('  border: 1px solid var(--border);')
w('  border-radius: var(--radius-lg);')
w('  padding: 20px;')
w('  margin-top: 16px;')
w('  display: none;')
w('}')
w('.bench-config.open { display: block; }')
w('.form-row {')
w('  display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));')
w('  gap: 12px; margin-bottom: 16px;')
w('}')
w('.form-group { display: flex; flex-direction: column; gap: 6px; }')
w('.form-label { font-size: 12px; font-weight: 600; color: var(--text-dim); }')
w('.form-input {')
w('  background: var(--card); border: 1px solid var(--border);')
w('  border-radius: var(--radius); color: var(--text);')
w('  padding: 8px 12px; font-size: 13px;')
w('  outline: none; transition: border-color .2s;')
w('}')
w('.form-input:focus { border-color: var(--accent); }')

# ─── Log terminal ────────────────────────────────────────────────────────────
w('.log-terminal {')
w('  background: #0a0e13;')
w('  border: 1px solid #1e2730;')
w('  border-radius: var(--radius);')
w('  padding: 14px 16px;')
w('  font-family: "Cascadia Code", "Fira Code", "JetBrains Mono", Consolas, monospace;')
w('  font-size: 12px;')
w('  color: #4caf50;')
w('  min-height: 200px;')
w('  max-height: 400px;')
w('  overflow-y: auto;')
w('  margin-top: 16px;')
w('  display: none;')
w('  line-height: 1.7;')
w('  white-space: pre-wrap;')
w('  word-break: break-all;')
w('}')
w('.log-terminal.open { display: block; }')
w('.log-line { color: #4caf50; }')
w('.log-line.info { color: #64b5f6; }')
w('.log-line.warn { color: #ffb74d; }')
w('.log-line.error { color: #e57373; }')
w('.log-line.done { color: #81c784; font-weight: bold; }')
w('.log-line.dim { color: #546e7a; }')

# ─── Buttons ─────────────────────────────────────────────────────────────────
w('.btn {')
w('  display: inline-flex; align-items: center; gap: 8px;')
w('  padding: 10px 20px; border-radius: var(--radius);')
w('  font-size: 14px; font-weight: 600; cursor: pointer;')
w('  border: 1px solid transparent;')
w('  transition: all .2s; outline: none;')
w('  text-decoration: none;')
w('}')
w('.btn:disabled { opacity: .5; cursor: not-allowed; }')
w('.btn-primary {')
w('  background: var(--accent); color: #0d1117;')
w('  border-color: var(--accent);')
w('}')
w('.btn-primary:hover:not(:disabled) { background: #79b8ff; border-color: #79b8ff; }')
w('.btn-arm {')
w('  background: var(--arm); color: #fff;')
w('  border-color: var(--arm);')
w('}')
w('.btn-arm:hover:not(:disabled) { background: #00aad9; border-color: #00aad9; }')
w('.btn-ghost {')
w('  background: transparent; color: var(--text-dim);')
w('  border-color: var(--border);')
w('}')
w('.btn-ghost:hover:not(:disabled) { color: var(--text); background: var(--card2); }')
w('.btn-sm { padding: 6px 14px; font-size: 12px; }')
w('.btn-danger { background: rgba(248,81,73,.1); color: var(--red); border-color: rgba(248,81,73,.3); }')
w('.btn-danger:hover:not(:disabled) { background: var(--red); color: #fff; }')

# ─── Spinner ─────────────────────────────────────────────────────────────────
w('.spinner {')
w('  width: 16px; height: 16px;')
w('  border: 2px solid rgba(255,255,255,.2);')
w('  border-top-color: currentColor;')
w('  border-radius: 50%;')
w('  animation: spin .7s linear infinite;')
w('}')
w('@keyframes spin { to { transform: rotate(360deg); } }')
w('.spinner.sm { width: 12px; height: 12px; }')

# ─── Try it live ─────────────────────────────────────────────────────────────
w('.prompt-area {')
w('  width: 100%; background: var(--card);')
w('  border: 1px solid var(--border);')
w('  border-radius: var(--radius);')
w('  color: var(--text); padding: 12px 14px;')
w('  font-size: 14px; resize: vertical; min-height: 80px;')
w('  font-family: inherit; outline: none;')
w('  transition: border-color .2s;')
w('}')
w('.prompt-area:focus { border-color: var(--accent); }')
w('.preset-btns { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }')
w('.preset-btn {')
w('  padding: 5px 12px; border-radius: 16px;')
w('  background: rgba(88,166,255,.08); color: var(--accent);')
w('  border: 1px solid rgba(88,166,255,.25);')
w('  font-size: 12px; cursor: pointer; transition: all .2s;')
w('}')
w('.preset-btn:hover { background: rgba(88,166,255,.18); }')
w('.response-box {')
w('  background: var(--card2); border: 1px solid var(--border);')
w('  border-radius: var(--radius); padding: 14px;')
w('  margin-top: 12px; display: none;')
w('}')
w('.response-box.open { display: block; }')
w('.response-content {')
w('  color: var(--text); font-size: 13px; line-height: 1.7;')
w('  white-space: pre-wrap; word-break: break-word;')
w('  max-height: 300px; overflow-y: auto;')
w('}')
w('.response-meta {')
w('  display: flex; gap: 16px; flex-wrap: wrap;')
w('  margin-top: 10px; padding-top: 10px;')
w('  border-top: 1px solid var(--border);')
w('}')
w('.response-meta-item { font-size: 12px; color: var(--text-dim); }')
w('.response-meta-item strong { color: var(--accent); }')

# ─── History table ────────────────────────────────────────────────────────────
w('.table-wrap {')
w('  overflow-x: auto;')
w('  border: 1px solid var(--border);')
w('  border-radius: var(--radius-lg);')
w('}')
w('table {')
w('  width: 100%; border-collapse: collapse;')
w('  font-size: 13px;')
w('}')
w('thead th {')
w('  background: var(--card2); color: var(--text-dim);')
w('  font-weight: 600; font-size: 11px; text-transform: uppercase;')
w('  letter-spacing: 0.6px; padding: 10px 14px;')
w('  text-align: left; border-bottom: 1px solid var(--border);')
w('  white-space: nowrap;')
w('}')
w('tbody tr {')
w('  border-bottom: 1px solid var(--border);')
w('  transition: background .15s;')
w('  cursor: pointer;')
w('}')
w('tbody tr:last-child { border-bottom: none; }')
w('tbody tr:hover { background: var(--card2); }')
w('tbody tr.selected { background: rgba(88,166,255,.08); }')
w('tbody td { padding: 10px 14px; color: var(--text); }')
w('.td-mono { font-family: monospace; font-size: 12px; color: var(--text-dim); }')

# ─── Raw JSON viewer ─────────────────────────────────────────────────────────
w('.json-viewer {')
w('  background: var(--card2); border: 1px solid var(--border);')
w('  border-radius: var(--radius); padding: 16px;')
w('  margin-top: 16px; display: none;')
w('}')
w('.json-viewer.open { display: block; }')
w('.json-content {')
w('  font-family: "Cascadia Code", Consolas, monospace;')
w('  font-size: 12px; color: #e6edf3;')
w('  white-space: pre; overflow-x: auto; max-height: 500px; overflow-y: auto;')
w('  line-height: 1.6;')
w('}')
w('.json-key   { color: #79c0ff; }')
w('.json-str   { color: #a5d6ff; }')
w('.json-num   { color: #f0883e; }')
w('.json-bool  { color: #d2a8ff; }')
w('.json-null  { color: #8b949e; }')

# ─── Sysinfo card ─────────────────────────────────────────────────────────────
w('.sysinfo-card {')
w('  background: var(--card); border: 1px solid var(--border);')
w('  border-radius: var(--radius-lg); padding: 20px;')
w('}')
w('.sysinfo-grid {')
w('  display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));')
w('  gap: 16px;')
w('}')
w('.sysinfo-item {}')
w('.sysinfo-label { font-size: 11px; color: var(--text-sub); text-transform: uppercase; letter-spacing: 0.6px; margin-bottom: 4px; }')
w('.sysinfo-value { font-size: 14px; color: var(--text); font-weight: 500; }')
w('.feature-pills { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 12px; }')
w('.offline-note {')
w('  display: flex; align-items: center; gap: 8px;')
w('  background: rgba(248,81,73,.06); border: 1px solid rgba(248,81,73,.2);')
w('  border-radius: var(--radius); padding: 10px 14px;')
w('  color: var(--text-dim); font-size: 13px; margin-bottom: 16px;')
w('}')
w('.offline-note.hidden { display: none; }')

# ─── Loading skeleton ─────────────────────────────────────────────────────────
w('.skeleton {')
w('  background: linear-gradient(90deg, var(--card2) 25%, #1e2530 50%, var(--card2) 75%);')
w('  background-size: 200% 100%;')
w('  animation: shimmer 1.5s infinite;')
w('  border-radius: 4px;')
w('}')
w('@keyframes shimmer { 0%{background-position:200% 0} 100%{background-position:-200% 0} }')
w('.skeleton-text { height: 14px; width: 80%; margin: 6px 0; }')
w('.skeleton-value { height: 32px; width: 60%; margin: 8px 0; }')

# ─── Misc ─────────────────────────────────────────────────────────────────────
w('.text-dim { color: var(--text-dim); }')
w('.text-sub { color: var(--text-sub); }')
w('.text-green { color: var(--green); }')
w('.text-red { color: var(--red); }')
w('.text-accent { color: var(--accent); }')
w('.text-arm { color: var(--arm); }')
w('.font-mono { font-family: monospace; }')
w('.divider { height: 1px; background: var(--border); margin: 16px 0; }')
w('.hidden { display: none !important; }')
w('.collapsible-toggle {')
w('  display: flex; align-items: center; justify-content: space-between;')
w('  cursor: pointer; padding: 12px 0;')
w('  border-top: 1px solid var(--border);')
w('  margin-top: 12px;')
w('  font-size: 13px; font-weight: 600; color: var(--text-dim);')
w('  transition: color .2s;')
w('  user-select: none;')
w('}')
w('.collapsible-toggle:hover { color: var(--text); }')
w('.chevron { transition: transform .2s; font-size: 10px; }')
w('.chevron.open { transform: rotate(180deg); }')

f.close()
print("CSS written")
