import pathlib

OUT = pathlib.Path("dashboard/index.html")
f = OUT.open("a", encoding="utf-8")

def w(s=""):
    f.write(s + "\n")

# Continue the HTML from where _writer.py left off (after CSS)
w('</style>')
w('</head>')
w('<body>')

# ─────────────────────────────────────────────────────────────────────────────
# HEADER
# ─────────────────────────────────────────────────────────────────────────────
w('<header>')
w('  <div class="header-inner">')
w('    <div class="logo">')
w('      <div class="logo-mark">SA</div>')
w('      <div class="logo-text">')
w('        <span class="logo-name">SpecArm</span>')
w('        <span class="logo-sub">Arm AI Optimization &middot; Speculative Decoding &middot; KleidiAI</span>')
w('      </div>')
w('    </div>')
w('    <div class="flex flex-center gap-12">')
w('      <nav class="nav-tabs" id="navTabs">')
w('        <button class="nav-tab active" data-section="overview">Overview</button>')
w('        <button class="nav-tab" data-section="benchmark">Benchmark</button>')
w('        <button class="nav-tab" data-section="try-it">Try It</button>')
w('        <button class="nav-tab" data-section="history">History</button>')
w('      </nav>')
w('      <div class="status-badge" id="statusBadge">')
w('        <div class="dot checking" id="statusDot"></div>')
w('        <span id="statusText">Checking&hellip;</span>')
w('      </div>')
w('    </div>')
w('  </div>')
w('</header>')

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────
w('<main class="container">')

# ──── OFFLINE NOTICE ────────────────────────────────────────────────────────
w('<div class="offline-note hidden" id="offlineNote">')
w('  <span>&#9888;&#65039;</span>')
w('  <span>Flask server unreachable &mdash; showing cached / placeholder data. Start <code>python dashboard/app.py</code> to activate live features.</span>')
w('</div>')

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 1 — Overview (sysinfo + comparison)
# ═══════════════════════════════════════════════════════════════════════════
w('<section class="section" id="section-overview">')
w('  <div class="section-header">')
w('    <h2 class="section-title"><span class="icon">&#x1F4BB;</span> System Overview</h2>')
w('    <p class="section-desc">AWS Graviton2 &mdash; t4g.small &mdash; llama.cpp + KleidiAI</p>')
w('  </div>')

# ── Sysinfo card ─────────────────────────────────────────────────────────
w('  <div class="sysinfo-card" id="sysinfoCard">')
w('    <div class="sysinfo-grid" id="sysinfoGrid">')
w('      <div class="sysinfo-item">')
w('        <div class="sysinfo-label">CPU</div>')
w('        <div class="sysinfo-value skeleton skeleton-value" id="si-cpu" style="min-width:160px"></div>')
w('      </div>')
w('      <div class="sysinfo-item">')
w('        <div class="sysinfo-label">Cores</div>')
w('        <div class="sysinfo-value skeleton skeleton-text" id="si-cores"></div>')
w('      </div>')
w('      <div class="sysinfo-item">')
w('        <div class="sysinfo-label">Memory</div>')
w('        <div class="sysinfo-value skeleton skeleton-text" id="si-memory"></div>')
w('      </div>')
w('      <div class="sysinfo-item">')
w('        <div class="sysinfo-label">OS / Arch</div>')
w('        <div class="sysinfo-value skeleton skeleton-text" id="si-os"></div>')
w('      </div>')
w('      <div class="sysinfo-item">')
w('        <div class="sysinfo-label">KleidiAI</div>')
w('        <div class="sysinfo-value skeleton skeleton-text" id="si-kleidiai"></div>')
w('      </div>')
w('    </div>')
w('    <div class="feature-pills" id="featurePills">')
w('      <!-- ISA feature pills injected here -->')
w('    </div>')
w('  </div>')

# ── Comparison ────────────────────────────────────────────────────────────
w('  <div class="section-header mt-24">')
w('    <h2 class="section-title"><span class="icon">&#x26A1;</span> Model Comparison</h2>')
w('    <p class="section-desc">Baseline (target only) vs Speculative Decoding (draft + target). Using two most recent benchmark runs.</p>')
w('  </div>')

w('  <div class="compare-wrap" id="compareWrap">')
w('    <!-- Left: baseline -->')
w('    <div class="compare-card baseline" id="baselineCard">')
w('      <div class="compare-card-header">')
w('        <div>')
w('          <div class="compare-card-label">Baseline Model</div>')
w('          <div class="compare-card-model">Qwen2.5-1.5B-Instruct &mdash; target only</div>')
w('        </div>')
w('        <span class="pill gray">Baseline</span>')
w('      </div>')
w('      <div id="baselineMetrics">')
w('        <div class="empty-compare"><span class="icon">&#128203;</span>Run a benchmark to populate baseline data.</div>')
w('      </div>')
w('    </div>')
w('    <!-- Center divider -->')
w('    <div class="compare-divider">')
w('      <div class="vs-circle">VS</div>')
w('      <div id="speedupBadge"></div>')
w('    </div>')
w('    <!-- Right: speculative -->')
w('    <div class="compare-card spec" id="specCard">')
w('      <div class="compare-card-header">')
w('        <div>')
w('          <div class="compare-card-label">Speculative Decoding</div>')
w('          <div class="compare-card-model">Qwen2.5-0.5B (draft) + Qwen2.5-1.5B (target)</div>')
w('        </div>')
w('        <span class="pill blue">Latest</span>')
w('      </div>')
w('      <div id="specMetrics">')
w('        <div class="empty-compare"><span class="icon">&#128203;</span>No benchmark results yet. Run a benchmark to see results.</div>')
w('      </div>')
w('    </div>')
w('  </div>')

# ── Category bar chart ────────────────────────────────────────────────────
w('  <div class="chart-wrap" id="chartWrap">')
w('    <div class="chart-title">Tokens/sec by Category &mdash; Baseline vs Speculative Decoding</div>')
w('    <svg id="category-chart" height="260" aria-label="Benchmark results by category"></svg>')
w('    <div id="chartLegend" class="flex gap-16 mt-8" style="font-size:12px;color:var(--text-dim);">')
w('      <span><span style="display:inline-block;width:10px;height:10px;background:var(--text-sub);border-radius:2px;margin-right:4px;"></span>Baseline</span>')
w('      <span><span style="display:inline-block;width:10px;height:10px;background:var(--accent);border-radius:2px;margin-right:4px;"></span>Speculative</span>')
w('    </div>')
w('  </div>')
w('</section>')

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 2 — Benchmark Runner
# ═══════════════════════════════════════════════════════════════════════════
w('<section class="section" id="section-benchmark">')
w('  <div class="section-header">')
w('    <h2 class="section-title"><span class="icon">&#x1F680;</span> Run Benchmark</h2>')
w('    <p class="section-desc">Trigger a new benchmark run on the remote llama-server and watch live output.</p>')
w('  </div>')

w('  <div class="flex flex-center gap-12 flex-wrap">')
w('    <button class="btn btn-primary" id="btnRunBench" onclick="toggleBenchConfig()">')
w('      <span class="icon">&#9654;</span> Run Benchmark')
w('    </button>')
w('    <button class="btn btn-ghost" id="btnCancelBench" onclick="cancelBenchmark()" style="display:none">')
w('      Cancel')
w('    </button>')
w('    <div id="benchStatusPill"></div>')
w('  </div>')

# ── Config panel ─────────────────────────────────────────────────────────
w('  <div class="bench-config" id="benchConfig">')
w('    <div class="form-row">')
w('      <div class="form-group">')
w('        <label class="form-label" for="cfgServerUrl">llama-server URL</label>')
w('        <input class="form-input" id="cfgServerUrl" type="text" value="http://13.211.208.159:8080" placeholder="http://..." />')
w('      </div>')
w('      <div class="form-group">')
w('        <label class="form-label" for="cfgModel">Model / Quant</label>')
w('        <input class="form-input" id="cfgModel" type="text" value="Q4_K_M" placeholder="Q4_K_M" />')
w('      </div>')
w('      <div class="form-group">')
w('        <label class="form-label" for="cfgTrials">Trials per prompt</label>')
w('        <input class="form-input" id="cfgTrials" type="number" value="3" min="1" max="10" />')
w('      </div>')
w('      <div class="form-group">')
w('        <label class="form-label" for="cfgMaxTokens">Max tokens</label>')
w('        <input class="form-input" id="cfgMaxTokens" type="number" value="64" min="16" max="512" />')
w('      </div>')
w('    </div>')
w('    <div class="flex gap-8">')
w('      <button class="btn btn-arm" id="btnStartBench" onclick="startBenchmark()">')
w('        <span>&#x1F3C3;</span> Start Benchmark')
w('      </button>')
w('      <button class="btn btn-ghost btn-sm" onclick="toggleBenchConfig()">Cancel</button>')
w('    </div>')
w('  </div>')

# ── Live log terminal ─────────────────────────────────────────────────────
w('  <div class="log-terminal" id="logTerminal" role="log" aria-live="polite"></div>')
w('</section>')

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 3 — Try It Live
# ═══════════════════════════════════════════════════════════════════════════
w('<section class="section" id="section-try-it">')
w('  <div class="section-header">')
w('    <h2 class="section-title"><span class="icon">&#x1F4AC;</span> Try It Live</h2>')
w('    <p class="section-desc">Send a prompt directly to the llama-server and see the response in real time.</p>')
w('  </div>')

w('  <div class="preset-btns" id="presetBtns">')
w('    <button class="preset-btn" onclick="setPreset(this)">Explain speculative decoding</button>')
w('    <button class="preset-btn" onclick="setPreset(this)">What is KleidiAI?</button>')
w('    <button class="preset-btn" onclick="setPreset(this)">Write a Python quicksort</button>')
w('    <button class="preset-btn" onclick="setPreset(this)">What is the capital of France?</button>')
w('    <button class="preset-btn" onclick="setPreset(this)">Explain Arm NEON SIMD in one paragraph</button>')
w('  </div>')

w('  <div class="flex flex-center gap-12 mb-8" style="flex-wrap:wrap">')
w('    <div class="form-group" style="flex:1;min-width:160px;max-width:220px">')
w('      <label class="form-label" for="tryServerUrl">Server URL</label>')
w('      <input class="form-input" id="tryServerUrl" type="text" value="http://13.211.208.159:8080" />')
w('    </div>')
w('    <div class="form-group" style="min-width:120px">')
w('      <label class="form-label" for="tryMaxTokens">Max tokens</label>')
w('      <input class="form-input" id="tryMaxTokens" type="number" value="256" min="16" max="1024" />')
w('    </div>')
w('    <div class="form-group" style="min-width:120px">')
w('      <label class="form-label" for="tryTemp">Temperature</label>')
w('      <input class="form-input" id="tryTemp" type="number" value="0.7" min="0" max="2" step="0.1" />')
w('    </div>')
w('  </div>')

w('  <textarea class="prompt-area" id="promptInput" placeholder="Type your prompt here&hellip;" rows="4"></textarea>')
w('  <div class="flex gap-8 mt-8">')
w('    <button class="btn btn-primary" id="btnSendPrompt" onclick="sendPrompt()">')
w('      <span>&#x27A4;</span> Send Prompt')
w('    </button>')
w('    <button class="btn btn-ghost btn-sm" onclick="clearResponse()">Clear</button>')
w('  </div>')

w('  <div class="response-box" id="responseBox">')
w('    <div style="font-size:11px;color:var(--text-sub);text-transform:uppercase;letter-spacing:.8px;margin-bottom:8px;">Response</div>')
w('    <div class="response-content" id="responseContent"></div>')
w('    <div class="response-meta" id="responseMeta"></div>')
w('  </div>')
w('</section>')

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 4 — History Table + JSON Viewer
# ═══════════════════════════════════════════════════════════════════════════
w('<section class="section" id="section-history">')
w('  <div class="section-header flex-between">')
w('    <div>')
w('      <h2 class="section-title"><span class="icon">&#x1F4CA;</span> Benchmark History</h2>')
w('      <p class="section-desc">All saved benchmark runs. Click a row to compare with the latest.</p>')
w('    </div>')
w('    <button class="btn btn-ghost btn-sm" onclick="loadResults()">')
w('      <span id="refreshIcon">&#x21BB;</span> Refresh')
w('    </button>')
w('  </div>')

w('  <div id="historyTableWrap">')
w('    <div class="flex-center gap-8" style="color:var(--text-dim);padding:20px;">')
w('      <div class="spinner"></div> Loading history&hellip;')
w('    </div>')
w('  </div>')

# ── Raw JSON viewer ───────────────────────────────────────────────────────
w('  <div class="collapsible-toggle" id="jsonToggle" onclick="toggleJsonViewer()" style="display:none">')
w('    <span id="jsonToggleLabel">&#x1F4C4; Raw JSON &mdash; <span id="jsonFilename"></span></span>')
w('    <span class="chevron" id="jsonChevron">&#9660;</span>')
w('  </div>')
w('  <div class="json-viewer" id="jsonViewer">')
w('    <div class="json-content" id="jsonContent"></div>')
w('  </div>')
w('</section>')

w('</main>')

# ── Footer ────────────────────────────────────────────────────────────────
w('<footer style="border-top:1px solid var(--border);padding:20px 0;margin-top:8px;">')
w('  <div class="container flex-between" style="flex-wrap:wrap;gap:12px">')
w('    <span style="color:var(--text-sub);font-size:12px;">SpecArm &mdash; Arm AI Optimization Hackathon &middot; AWS Graviton2 t4g.small &middot; llama.cpp + KleidiAI</span>')
w('    <span style="color:var(--text-sub);font-size:12px;" id="footerResultCount"></span>')
w('  </div>')
w('</footer>')

f.close()
print("HTML structure written")
